// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdpVSy4DzLTzJkgEhbpfLb0ToX3p4NYEE',
    appId: '1:185586111617:ios:6370b8c91220d0f8116980',
    messagingSenderId: '185586111617',
    projectId: 'mygarden-6de95',
    databaseURL: 'https://mygarden-6de95-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mygarden-6de95.firebasestorage.app',
    iosBundleId: 'com.example.myGarden2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdpVSy4DzLTzJkgEhbpfLb0ToX3p4NYEE',
    appId: '1:185586111617:ios:6370b8c91220d0f8116980',
    messagingSenderId: '185586111617',
    projectId: 'mygarden-6de95',
    databaseURL: 'https://mygarden-6de95-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mygarden-6de95.firebasestorage.app',
    iosBundleId: 'com.example.myGarden2',
  );

}